tyk_gateway:
    image: tyk-gateway
    links:
        - tyk_redis:redis
        - tyk_mongo:mongo
    ports:
        - "80:8080"
        - "8080:8080"
tyk_analytics:
    image: tyk-analytics
    links:
        - tyk_redis:redis
        - tyk_mongo:mongo
        - tyk_gateway:tyk_gateway
    ports:
        - "3000:3000"
tyk_redis:
    image: redis:latest
    hostname: redis
tyk_mongo_data:
    image: mongo:latest
    command: ["/bin/true"]
    volumes:
        - /data/db
tyk_mongo:
    image: mongo:latest
    command: ["mongod", "--smallfiles"]
    hostname: mongo
    volumes_from:
        - tyk_mongo_data
    ports:
        - "27017:27017"
